services:
  controller:
    build:
      context: ./controller
      dockerfile: Dockerfile
    environment:
      CONTROLLER_ID: "${CONTROLLER_ID:-ctrl-0001}"
      CITY: "${CITY:-moscow}"

      # В реальном деплое здесь буду dns/адрес MQTT брокер в нашей сети
      MQTT_HOST: "${MQTT_HOST:-emqx}"
      MQTT_PORT: "${MQTT_PORT:-1883}"

      MQTT_TELEMETRY_TOPIC_PREFIX: "${MQTT_TELEMETRY_TOPIC_PREFIX:-v1/telemetry}"
      MQTT_COMAND_TOPIC_PREFIX: "${MQTT_COMMAND_TOPIC_PREFIX:-v1/command}"
      MQTT_ACK_TOPIC_PREFIX: "${MQTT_ACK_TOPIC_PREFIX:-v1/ack}"
      MQTT_QOS: "${MQTT_QOS:-1}"

      SEND_INTERVAL_SEC: "${SEND_INTERVAL_SEC:-5}"
      BASE_WATTS: "${BASE_WATTS:-120}"
      NOISE_WATTS: "${NOISE_WATTS:-30}"
      ENABLE_ACK: "${ENABLE_ACK:-0}"